version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - shared

  lessons:
    ports:
      - "8765:8080"
    environment:
      - PORT=8080
    image: michaellazebny/lessons:latest
    container_name: lessons
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    driver: bridge

volumes:
  caddy_data:
    external: true
  caddy_config: